name: Run tests

on:
  push:
    branches:
      - '**'
  
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    env:
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_USER: ${{ vars.POSTGRES_USER }}
        POSTGRES_DBNAME: ${{ vars.POSTGRES_DBNAME }}
        POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
        REACT_APP_BACKEND_URL: ${{ vars.REACT_APP_BACKEND_URL }}
        AES_ENCRYPTION_KEY: ${{ secrets.AES_ENCRYPTION_KEY }}
        AES_INITIALISATION_VECTOR: ${{ secrets.AES_INITIALISATION_VECTOR }}
        JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        FLASK_APP_CLIENT_URL: ${{ vars.FLASK_APP_CLIENT_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Start PostgreSQL DB instance with Docker Compose
        run: docker compose -f compose.db.yml up -d
      
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Activate virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Run backend unit tests
        run: |
          pip install -r requirements.txt
          pip list
          pytest -s
        working-directory: backend
      
      - name: Stop running PostgreSQL DB container
        if: always()
        run: docker compose -f compose.db.yml down



  integration-tests:
    needs: unit-tests
    name: Integration tests
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Pass
        if: false
        run: echo "Pass"